/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CoinRouteImport } from './routes/coin'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LiveRouteImport } from './routes/live'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StatusRouteImport } from './routes/status'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as WalletTransactionsTransactionIdRouteImport } from './routes/wallet/transactions/$transactionId'
import { Route as ApiPublicCronShopCleanupRouteImport } from './routes/api/public/cron/shop-cleanup'
import { Route as ApiPublicCronStatusCleanupRouteImport } from './routes/api/public/cron/status-cleanup'
import { Route as ApiPublicCronWalletCleanupRouteImport } from './routes/api/public/cron/wallet-cleanup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinRoute = CoinRouteImport.update({
  id: '/coin',
  path: '/coin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletTransactionsTransactionIdRoute =
  WalletTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => WalletRoute,
  } as any)
const ApiPublicCronShopCleanupRoute =
  ApiPublicCronShopCleanupRouteImport.update({
    id: '/api/public/cron/shop-cleanup',
    path: '/api/public/cron/shop-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronStatusCleanupRoute =
  ApiPublicCronStatusCleanupRouteImport.update({
    id: '/api/public/cron/status-cleanup',
    path: '/api/public/cron/status-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWalletCleanupRoute =
  ApiPublicCronWalletCleanupRouteImport.update({
    id: '/api/public/cron/wallet-cleanup',
    path: '/api/public/cron/wallet-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/coin': typeof CoinRoute
  '/contacts': typeof ContactsRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/status': typeof StatusRoute
  '/wallet': typeof WalletRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/wallet/transactions/$transactionId': typeof WalletTransactionsTransactionIdRoute
  '/api/public/cron/shop-cleanup': typeof ApiPublicCronShopCleanupRoute
  '/api/public/cron/status-cleanup': typeof ApiPublicCronStatusCleanupRoute
  '/api/public/cron/wallet-cleanup': typeof ApiPublicCronWalletCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/coin': typeof CoinRoute
  '/contacts': typeof ContactsRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/status': typeof StatusRoute
  '/wallet': typeof WalletRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/wallet/transactions/$transactionId': typeof WalletTransactionsTransactionIdRoute
  '/api/public/cron/shop-cleanup': typeof ApiPublicCronShopCleanupRoute
  '/api/public/cron/status-cleanup': typeof ApiPublicCronStatusCleanupRoute
  '/api/public/cron/wallet-cleanup': typeof ApiPublicCronWalletCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/coin': typeof CoinRoute
  '/contacts': typeof ContactsRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/status': typeof StatusRoute
  '/wallet': typeof WalletRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/wallet/transactions/$transactionId': typeof WalletTransactionsTransactionIdRoute
  '/api/public/cron/shop-cleanup': typeof ApiPublicCronShopCleanupRoute
  '/api/public/cron/status-cleanup': typeof ApiPublicCronStatusCleanupRoute
  '/api/public/cron/wallet-cleanup': typeof ApiPublicCronWalletCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calls'
    | '/coin'
    | '/contacts'
    | '/feed'
    | '/live'
    | '/new'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/status'
    | '/wallet'
    | '/chat/$id'
    | '/api/webhooks/stripe'
    | '/wallet/transactions/$transactionId'
    | '/api/public/cron/shop-cleanup'
    | '/api/public/cron/status-cleanup'
    | '/api/public/cron/wallet-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calls'
    | '/coin'
    | '/contacts'
    | '/feed'
    | '/live'
    | '/new'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/status'
    | '/wallet'
    | '/chat/$id'
    | '/api/webhooks/stripe'
    | '/wallet/transactions/$transactionId'
    | '/api/public/cron/shop-cleanup'
    | '/api/public/cron/status-cleanup'
    | '/api/public/cron/wallet-cleanup'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calls'
    | '/coin'
    | '/contacts'
    | '/feed'
    | '/live'
    | '/new'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/status'
    | '/wallet'
    | '/chat/$id'
    | '/api/webhooks/stripe'
    | '/wallet/transactions/$transactionId'
    | '/api/public/cron/shop-cleanup'
    | '/api/public/cron/status-cleanup'
    | '/api/public/cron/wallet-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CallsRoute: typeof CallsRoute
  CoinRoute: typeof CoinRoute
  ContactsRoute: typeof ContactsRoute
  FeedRoute: typeof FeedRoute
  LiveRoute: typeof LiveRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  StatusRoute: typeof StatusRoute
  WalletRoute: typeof WalletRouteWithChildren
  ChatIdRoute: typeof ChatIdRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiPublicCronShopCleanupRoute: typeof ApiPublicCronShopCleanupRoute
  ApiPublicCronStatusCleanupRoute: typeof ApiPublicCronStatusCleanupRoute
  ApiPublicCronWalletCleanupRoute: typeof ApiPublicCronWalletCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin': {
      id: '/coin'
      path: '/coin'
      fullPath: '/coin'
      preLoaderRoute: typeof CoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/transactions/$transactionId': {
      id: '/wallet/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/wallet/transactions/$transactionId'
      preLoaderRoute: typeof WalletTransactionsTransactionIdRouteImport
      parentRoute: typeof WalletRoute
    }
    '/api/public/cron/shop-cleanup': {
      id: '/api/public/cron/shop-cleanup'
      path: '/api/public/cron/shop-cleanup'
      fullPath: '/api/public/cron/shop-cleanup'
      preLoaderRoute: typeof ApiPublicCronShopCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/status-cleanup': {
      id: '/api/public/cron/status-cleanup'
      path: '/api/public/cron/status-cleanup'
      fullPath: '/api/public/cron/status-cleanup'
      preLoaderRoute: typeof ApiPublicCronStatusCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/wallet-cleanup': {
      id: '/api/public/cron/wallet-cleanup'
      path: '/api/public/cron/wallet-cleanup'
      fullPath: '/api/public/cron/wallet-cleanup'
      preLoaderRoute: typeof ApiPublicCronWalletCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletRouteChildren {
  WalletTransactionsTransactionIdRoute: typeof WalletTransactionsTransactionIdRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletTransactionsTransactionIdRoute: WalletTransactionsTransactionIdRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CallsRoute: CallsRoute,
  CoinRoute: CoinRoute,
  ContactsRoute: ContactsRoute,
  FeedRoute: FeedRoute,
  LiveRoute: LiveRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  StatusRoute: StatusRoute,
  WalletRoute: WalletRouteWithChildren,
  ChatIdRoute: ChatIdRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiPublicCronShopCleanupRoute: ApiPublicCronShopCleanupRoute,
  ApiPublicCronStatusCleanupRoute: ApiPublicCronStatusCleanupRoute,
  ApiPublicCronWalletCleanupRoute: ApiPublicCronWalletCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
