/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as ApiPublicCronStatusCleanupRouteImport } from './routes/api/public/cron/status-cleanup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronStatusCleanupRoute =
  ApiPublicCronStatusCleanupRouteImport.update({
    id: '/api/public/cron/status-cleanup',
    path: '/api/public/cron/status-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/feed': typeof FeedRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/status': typeof StatusRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/public/cron/status-cleanup': typeof ApiPublicCronStatusCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/feed': typeof FeedRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/status': typeof StatusRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/public/cron/status-cleanup': typeof ApiPublicCronStatusCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/contacts': typeof ContactsRoute
  '/feed': typeof FeedRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/status': typeof StatusRoute
  '/chat/$id': typeof ChatIdRoute
  '/api/public/cron/status-cleanup': typeof ApiPublicCronStatusCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calls'
    | '/contacts'
    | '/feed'
    | '/new'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/status'
    | '/chat/$id'
    | '/api/public/cron/status-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calls'
    | '/contacts'
    | '/feed'
    | '/new'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/status'
    | '/chat/$id'
    | '/api/public/cron/status-cleanup'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calls'
    | '/contacts'
    | '/feed'
    | '/new'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/status'
    | '/chat/$id'
    | '/api/public/cron/status-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CallsRoute: typeof CallsRoute
  ContactsRoute: typeof ContactsRoute
  FeedRoute: typeof FeedRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  StatusRoute: typeof StatusRoute
  ChatIdRoute: typeof ChatIdRoute
  ApiPublicCronStatusCleanupRoute: typeof ApiPublicCronStatusCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/status-cleanup': {
      id: '/api/public/cron/status-cleanup'
      path: '/api/public/cron/status-cleanup'
      fullPath: '/api/public/cron/status-cleanup'
      preLoaderRoute: typeof ApiPublicCronStatusCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CallsRoute: CallsRoute,
  ContactsRoute: ContactsRoute,
  FeedRoute: FeedRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  StatusRoute: StatusRoute,
  ChatIdRoute: ChatIdRoute,
  ApiPublicCronStatusCleanupRoute: ApiPublicCronStatusCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
